### ISSUE TITLE
Staging QA for Calitp.org changes 2023

### ISSUE THREAD

**Issue by mrose914** [cal-itp/calitp.org#157]
Creating a ticket to document any findings from our internal review of https://staging.calitp.org/ prior to pushing those changes live. 

**Updates:**

- [x] Remove "Understanding Merchant Service Charges" from Resources page (per request of Payments team, this is not yet ready for public consumption) #160 
- [x] #179
- [x] #180
- [x] #168
- [x] #169
- [x] #170
- [x] #171
- [x] #172
- [x] #174
- [x] #176
- [x] #177
- [x] #178
- [x] #173

**Comment by machikoyasuda** [comment]
> Updates:

- Merchant Service Exchange resource removed: https://github.com/cal-itp/calitp.org/pull/160

@mrose914

**Comment by esquared415** [comment]
@mrose914 I read all text and think:
- Text we crafted for new site looks good. 
- I'd like to make the summary headlines consistent on the Resources and Press page links. Is there a spreadsheet where would you like me to make these edits?

Q: Need me to check all web links too?

**Comment by segacy1** [comment]
Hello! Adding my edits for Press and Resource here: 

**General**
Pills
- Could you please make padding on either side of the text within the pills 8px
Rhombus
- Make space between the title and the body text 8 px
- Make space between body text and filters 32px
- Is it possible that when you get to the mobile breakpoint, the padding around the text in the rhombus decreases to 40px top and bottom? 

**Press**
Could you make the padding between the rhombus and the first press link the same as the padding between the rhombus and the “Case Studies” title on Resources?

**Press Release**
- The blue links don’t change to dark blue on hover
- I can’t tell if the top and bottom padding around the line break are the same—there might be extra on the bottom. Could you make them the same?
<img width="863" alt="Screenshot 2023-06-09 at 8 14 03 AM" src="https://github.com/cal-itp/calitp.org/assets/33331853/68f45362-e549-47d8-ac9b-029deb4c258f">

**Resources**
- Could the padding be the same on either side of the line breaks between the last article and the next title? In Figma I have it as 40px on either side of the line break. Should look like this
<img width="741" alt="Screenshot 2023-06-09 at 8 14 33 AM" src="https://github.com/cal-itp/calitp.org/assets/33331853/2f3e3bd9-b14a-40e8-996e-651754e24029">
- I don’t think this is a big deal but curious to hear your thoughts on what happens when a section doesn’t have any content (ex: Benefits/Case Studies). Is it possible to have the section title disappear from the results?

**Comment by thekaveman** [comment]
Thank you for all this feedback @segacy1! I updated the main description in this issue with tasks for each, please let me know (or edit!) if I missed anything or mischaracterized anything.

> The rounded rectangle background is split into 2 sections.

Can you share more details about the browser and screen size you're seeing this behavior? I am not able to reproduce in Chrome or Firefox at the smallest mobile size (320px wide):

(_please forgive the weird colors, for some reason my screenshots don't come through as the true color on the page_)

**Chrome:**

![image](https://github.com/cal-itp/calitp.org/assets/1783439/166d04bb-5de5-4625-952b-bd962b120520)

**Firefox:**

![image](https://github.com/cal-itp/calitp.org/assets/1783439/012eb8a5-6051-4cf6-882f-a0bdfb940183)

**Comment by segacy1** [comment]
I’ve never replied to GitHub by email so I hope this works! I’m seeing it on my iPhone 12 Pro with ChromeSent from my iPhoneOn Jun 9, 2023, at 12:22 PM, Kegan Maher ***@***.***> wrote:﻿
Thank you for all this feedback @segacy1! I updated the main description in this issue with tasks for each, please let me know (or edit!) if I missed anything or mischaracterized anything.

The rounded rectangle background is split into 2 sections.

Can you share more details about the browser and screen size you're seeing this behavior? I am not able to reproduce in Chrome or Firefox at the smallest mobile size (320px wide):
(please forgive the weird colors, for some reason my screenshots don't come through as the true color on the page)
Chrome:

Firefox:

**Comment by segacy1** [comment]
Adding in my notes for the homepage!

Is it possible to have the numbered list of goals in line with the rest of the text like this: 
<img width="811" alt="Screenshot 2023-06-09 at 4 02 38 PM" src="https://github.com/cal-itp/calitp.org/assets/33331853/d55f5819-6a6d-4380-a5fb-95cd844363fa">


**Initiative Rhombus:** 
1. Could we center the content within the rhombus? There is more padding on the left side (up until tablet view?). 
<img width="1289" alt="Screenshot 2023-06-09 at 4 03 12 PM" src="https://github.com/cal-itp/calitp.org/assets/33331853/d9bdc81d-b011-4a68-b82a-77de7f628eec">
2. Could we make the space between all sections 40px desktop like this: 
<img width="801" alt="Screenshot 2023-06-09 at 3 51 52 PM" src="https://github.com/cal-itp/calitp.org/assets/33331853/0aeffe31-b180-456f-ae7d-167bc5623a46">
and 28px on mobile (32px is okay too if you’d prefer divisible by 8)?
3. The padding between the links in the Recent News and Resources sections is different. Could they all be 8px between?

Contact Rhombuses:
1. Could we make the top/bottom padding for text within the rhombus 24px? Feels a little tight. 
2. On mobile, the rectangles are full-width to the edge of the screen. Can we make it full width to our normal content margin. 


Nav
I suppose we don’t need the “About the project” link in our top navigation anymore, do we? Im going to look back and confirm if we ever formally discussed that. It used to jump down to the bottom of the page where the _about us_ content used to be, but now that content is right above the fold cc: @esquared415

**Comment by thekaveman** [comment]
@segacy1:

> Nav
I suppose we don’t need the “About the project” link in our top navigation anymore, do we? Im going to look back and confirm if we ever formally discussed that. That link used to jump down to the bottom of the page where the about us content used to be, but now that content sits right below the fold cc: @esquared415

This is now the nav link to the homepage, so I think we should keep it. Open to different wording if this seems too long/not correct anymore.

**Comment by segacy1** [comment]
True—another option would be to have the logo in the nav act as the link to home like on mobimart, but I don't think this should be a blocker either way!

**Comment by thekaveman** [comment]
@segacy1 True! And in fact the logo does also link back to the homepage. We'll see if @esquared415 wants to weigh in, otherwise I say we leave it as-is for now.

**Comment by esquared415** [comment]
@thekaveman @segacy1 I think it's useful to have "About the project" nav option when you are on Resources or Press page.
