### ISSUE TITLE
Update Resource/Press summary headlines

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/calitp.org#179]
Initial assignment for @esquared415, review the spreadsheet of resources/press here: https://docs.google.com/spreadsheets/d/1xJpgr8JBG9TgZF2mHB8Vjnhu453No4dHoNjFIhb0FQw/edit#gid=0

**Comment by esquared415** [comment]
@thekaveman A few Qs: 

1. To craft new heds, I should update Column F "Title (for calitp.org)" on tracker spreadsheet?
2. Any max character counts to be aware of?
3. Will all links be posted on calitp.org? _(I don't yet understand the hierarchy of how links are chosen / ranked and where they are lifted from for publishing.)_
4. If I have a new link (such as MobilityData press release that's ready now, or Far North Group press release that should be ready later this week), should I add them to the tracker spreadsheet—and tag anyone or create a ticket?

Thanks!!

**Comment by thekaveman** [comment]
Thank you @esquared415!

1. Yes, Column F is the one we used to source headings for the website. Please update this column!
2. Shorter is always better/snappier for the web, but there is no absolute maximum we need to be worried about. Consider the layout of the [Press](https://staging.calitp.org/press) and [Resources](https://staging.calitp.org/resources) lists, but also how each show up on the [homepage](https://staging.calitp.org) under the "Initiatives" section (which is slightly more space constrained than the individual list pages).
3. I think @mrose914 is probably better positioned to answer this, I'm not exactly sure what would/should rise to the level of posting on calitp.org, though I do tend to default to "more is better" now that we have a clean layout with which to present them. We have already removed one of the initial Resources as the Payments team indicated it was not yet ready for public consumption.
4. Yes, please feel free to add new items to the spreadsheet! Please try and fill out as much detail (the columns) as you can, as we need specific items such as Category Type (Column B), Tag (Column D), and Date (Column H). After this initial push, we will be introducing some simpler forms here in GitHub to make it easier for those such as yourself to request additional items be posted (Resources, Press).

In general, may I ask that for any _rows_ that you edit/add, can you please highlight the row to make it more obvious for us which ones changed?

LMK if this makes sense or if you have any additional questions.

**Comment by esquared415** [comment]
@thekaveman This all makes sense—thank you! I will work on this on my train ride home from SAC this evening. 😄

**Comment by esquared415** [comment]
@thekaveman  Update: Working on this now (I didn't take the early train home. 🥲 )

**Comment by machikoyasuda** [comment]
@esquared415 Please comment here and at-mention me when the Google Spreadsheet is ready for engineering. Thank you.

**Comment by esquared415** [comment]
Hi @thekaveman and @machikoyasuda! I am done with my updates to the [Customer Resource Content Catalog](https://docs.google.com/spreadsheets/d/1xJpgr8JBG9TgZF2mHB8Vjnhu453No4dHoNjFIhb0FQw/edit#gid=0). 

_Things I did_:
- Changed all Titles in Column F, making sure that they are consistently Sentence case (as is the _case_, har har, for the rest of Calitp.org and for Mobi Mart). All edits are highlighted (under Column F).
- Added Row 22 (and completed all required cells) for the new joint press release with MobilityData. All edits are highlighted (Row 22).
- Struck-through row 10 to reflect my request to delete from Calitp.org the old DMV-workflow-oriented Fact Sheet about Benefits. All edits + Note are highlighted (Row 10). Realized afterward that Machiko had noticed the same thing—thank you! (Not sure why that Fact Sheet was put on the Customer Resource Content Catalog—I see its Note in cell 10L says it "might be outdated"—but I'm grateful we caught it in time.)

_Requests:_
- [ ] Please change "Case Studies" to **Case studies** _(sentence case)_
- [ ] Please change "Fact Sheets & Overviews" to **Fact sheets & overviews** _(sentence case)_

_Questions:_
- Machiko, I'm grateful you scoured [Cal-ITP Transit Benefits Overview_May 2023.pdf](https://drive.google.com/file/d/1UhNTnJAEABnCOFFZ-1xBHDoTYe322t-G/view) and discovered that slide 30 still contains a reference to the DMV. I didn't work on that deck and can't edit the PDF version we've linked, so I'm hoping that @o-ram can either grant me access to the slide deck or make the change (Olivia, for visual on this, please see Machiko's [note above](https://github.com/cal-itp/calitp.org/issues/179#issuecomment-1592123299). We will then need to regenerate the PDF, which could change the link that's in the [Customer Resource Content Catalog](https://docs.google.com/spreadsheets/d/1xJpgr8JBG9TgZF2mHB8Vjnhu453No4dHoNjFIhb0FQw/edit#gid=0).
- Kegan and Machiko, when's the best time to add more press releases and media coverage to the Content Catalog from our [Cal-ITP Media Coverage and Publications tracker](https://docs.google.com/spreadsheets/d/12zdDDRArtyXmm1wZJk4-vq1KvF8aZ9BWrIBIM4T7R3w/edit#gid=1455215505)? Jess and I have added tons of links that I'd be happy to prioritize to just the good stuff for Calitp.org. I would of course like to do this before launch, but I guess I'm asking if now's the time because I'm not sure why we have such a relatively small number of articles and releases listed on the Content Catalog (I didn't participate in populating the Content Catalog, so I want to make sure I'm ok to flesh out our Press offerings).

Thanks, all!
