### ISSUE TITLE
Make "About the project" navbar link jump to homepage project description

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/calitp.org#180]
~MobiMart does not have a separate homepage link, it only uses the logo in the nav.~

See updated description in comment below: https://github.com/cal-itp/calitp.org/issues/180#issuecomment-1592022357

**Comment by thekaveman** [comment]
Just to clarify @esquared415: the logo already links to the homepage. 

This question was: should we _remove_ the "About the project" link (thus only having the logo to link back to the homepage) - matching the behavior of MobiMart.

**Comment by thekaveman** [comment]
Closing this as not a concern for now. We can easily remove/change this nav link in the future if we decide we need to.

**Comment by esquared415** [comment]
@thekaveman Just saw this. Thank you for clarifying. I do think we can keep the "About this project" link in the navbar (in addition to the logo link). (And unless you're looking at a different version of Mobi Mart than I am, Mobi Mart _does_ have "About" in the navbar + a linked logo back to the homepage:
<img width="1272" alt="Screen Shot 2023-06-14 at 2 10 26 PM" src="https://github.com/cal-itp/calitp.org/assets/50693483/b5673516-075a-4dc5-b50a-3448338d7360">)

In restudying these two sites and their navbar actions side by side, could we link calitp.org's "About this project" to just under the fold, where the project description is? 
<img width="1164" alt="Screen Shot 2023-06-14 at 2 17 47 PM" src="https://github.com/cal-itp/calitp.org/assets/50693483/641659e5-60ef-4614-b0f8-b57f16ec050d">

Screengrab above illustrates what I'm suggesting—a slight jump down on the page (instead of the headline and graphic that takes up all above-the-fold space).

**Comment by thekaveman** [comment]
@esquared415:

> Mobi Mart does have "About" in the navbar + a linked logo back to the homepage

MobiMart has a specific "About" page that that navbar links to, rather than a section on the homepage. But I think we have a solution to this pending review from the other engineers.
