### ISSUE TITLE
Unable to move between category selectors on mobile for homepage

### ISSUE THREAD

**Issue by mrose914** [cal-itp/calitp.org#229]
To reproduce: 

- Go to calitp.org in Mobile Safari
- Scroll down to Explore our Initiatives 
- Click on other Categories 

I am only able to click on GTFS. Once on GTFS however, I cannot click on any other category (Benefits or Contactless Payments)

**Comment by thekaveman** [comment]
Confirmed this issue on Android FF and Chrome.

Not an issue on Desktop browsers as far as I can tell.

**Comment by machikoyasuda** [comment]
The fix for this is adding `d-none d-lg-block` to `<svg class="position-absolute">`, so that it'll look like `position-absolute d-none d-lg-block`. It's the transparent rhombus-shaped SVG that is necessary for shaping the Initiatives into a rhombus. But it's only necessary for lg size screens and up. It can be set to display: none in mobile. It's blocking the button area.
