### ISSUE TITLE
Design Press Release content page

### ISSUE THREAD

**Issue by mrose914** [cal-itp/calitp.org#82]
Confirm the following: 

- Is it a requirement to publish press releases as pdfs or is an html page OK? (We will now have a dedicated page for all Press so we can provide links / storage is simpler) 
- Do we intend to link to Press posted on other sites? eg, a link to the NYT talking about Cal ITP?

**Comment by esquared415** [comment]
@mrose914 
_Q1a: Is it a requirement to publish press releases as pdfs or is an html page OK? (We will now have a dedicated page for all Press so we can provide links / storage is simpler)_
A1a: By html page, do you mean like a long-running inline blog post? (If so, could you point me to a mock-up of what this would look like?) 

Q1b for you: Which 3 press releases are you looking at? We have lots of releases (and media coverage) on this list. 

Q1c for you: Are we limited to how many releases and articles we can post by either number or age of the pieces?


_Q2: Do we intend to link to Press posted on other sites? eg, a link to the NYT talking about Cal ITP?_
A2: I would love to see a mock-up of options. I'm not sure what you're envisioning, but I don't think that we should, say, lift and reprint text from a media site, and I think that a blog post that summarizes the article would get repetitive (plus require more work). So linking to either a headline or a headline and subhead or a screengrab with article URL are the best possibilities I can think of. But what were you and @segacy1 envisioning?

**Comment by esquared415** [comment]
Hi again @mrose914 and @segacy1. I saw @angela-tran's #92 about Press page and spotted the [Figma mock-up](https://www.figma.com/file/TfWk1iDHdlt7bSA3DjQuQv/Mobility-Marketplace?node-id=5305-29411).

The mock-up helped refresh me about how the Press page will be laid out, including that it will include a mix of our Press Releases and Media coverage.  

It looks like it will contain just hyperlinked Headlines (of either PR or Media story) with content-area tags (do you need help defining an initial set?) + date of publication (a field I hope we can control, so we can post some of our "older" releases).

I'm still not understanding what is meant by HTML page vs. PDF—perhaps you mean posting the Cal-ITP logo (and any partner logos) and PR content directly as a stand-alone webpage instead of uploading as a PDF to link to? Thanks in advance for clarifying. I do not have a preference, btw—you let me know what makes the most sense.

**Comment by thekaveman** [comment]
> @esquared415: I'm still not understanding what is meant by HTML page vs. PDF—perhaps you mean posting the Cal-ITP logo (and any partner logos) and PR content directly as a stand-alone webpage instead of uploading as a PDF to link to?

> @mrose914: Our main question is whether we will continue the plan of writing a press release and then turning it into a pdf that we host v. just writing it like an article on a new site, eg calitp.org/press-about-agency-xyz. The former works just fine but at some point we will have to think about storage of all of those files (and the impacts of needing to make edits to a source doc > re-upload)

@esquared415 to hopefully clarify some more:

We would ideally move away from using PDFs to publish _Cal-ITP's own_ press releases. We would rather take the same content that would go in the PDF, and have it show up on a (standard, designed) page template directly in the website. This is much simpler to maintain than a PDF, and more search and accessibility friendly.

For linking to _external press releases_ that were not created by Cal-ITP (but maybe mention something about Cal-ITP and thus still worthy of highlighting) we would simply provide a link directly to that external content, and NOT attempt to recreate that content in our website at all.

**Comment by thekaveman** [comment]
@segacy1: can you please design a page template for a Press Release content page. Something that fits in with the rest of the theme and structure, that can represent content like that found in this PDF: https://www.calitp.org/assets/Cal-ITP.Benefits.PressRelease.220921.pdf.

FYI @mrose914

**Comment by segacy1** [comment]
Hey @thekaveman, how does this look: https://www.figma.com/file/TfWk1iDHdlt7bSA3DjQuQv/Mobility-Marketplace?type=design&node-id=5979-35355&t=90wYBlt4OseIoZls-4

**Comment by thekaveman** [comment]
@segacy1 this is awesome! Thank you for the quick turnaround 👍
