### ISSUE TITLE
Implement new CSS styles

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/calitp.org#88]
The new designs in Figma show that we'll need to update our CSS. Design has worked on making styles across Cal-ITP websites more consistent, so we have changes to fonts, font-sizes, colors, and spacing.

This ticket does not involve re-ordering or removing any content. It is solely focused on the styles, so you'll need to do a bit of mapping between the old and new designs.

Also note this ticket does not include the navbar or footer -- those are to be done in #93.

**Comment by segacy1** [comment]
Hello! I wanted to ask if we could also have calitp.org use the same favicon as mobimart and benefits. It's this little guy:
<img width="51" alt="Screen Shot 2023-05-15 at 1 46 17 PM" src="https://github.com/cal-itp/calitp.org/assets/33331853/906dd065-f37d-46c2-b153-a2f487c5aa9b">

**Comment by thekaveman** [comment]
Keeping this on the backlog as we break out more specific CSS tickets.

**Comment by machikoyasuda** [comment]
CSS refactoring to do's:
- [ ] Convert all pixels to rems (as appropriate)
- [ ] Refactor out all CSS Grid
- [ ] Convert rgb variables to just numbers
- [ ] Variable-ize as many constants as possible
- [ ] Use CSS utilities for as many margins/paddings as possible

**Comment by segacy1** [comment]
Hey! Adding some additional information about link hover states. 

**Text Links**
To avoid accessibility issues with a subtle hover color on the various background colors we work with, I'm proposing that all links take the behavior of the current highlighted links on hover. Basically, on hover it would go from a solid line to a dashed line like this:
<img width="728" alt="Screen Shot 2023-06-06 at 3 25 18 PM" src="https://github.com/cal-itp/calitp.org/assets/33331853/7af55822-22ce-4cd4-a786-3b138da2e95a">

Right now in Figma, I've just been underlining the text with the default text formatting, which doesn't allow any changes. I remember from when we were updating buttons that the line weight looks different in figma vs. irl. Could we test the look by taking the current solid line/dashed line specs that are live and making it 1px bigger for me to see? I think what we have currently might be too thin. 

**Pills**
I realize we don't currently have a hover state for pills on MobiMart either. I have three ideas that wouldn't change the actual text color/work with our accessibility standards: 
<img width="648" alt="Screen Shot 2023-06-06 at 3 46 46 PM" src="https://github.com/cal-itp/calitp.org/assets/33331853/ebdac33c-86c6-4cb8-bbd5-3d6a369a97a3">

Please let me know if you have an opinion about this. I'd say we go with changing the outline opacity, since it's subtle and won't be confused with the active state which is expected to be a fill.

**Comment by thekaveman** [comment]
> Text Links

Agree with this proposal! Let's use the dashed underline for all hover effects on all links.

> Pills

I also agree that outline opacity seems like the best approach. The dashed outline feels a little strange/jarring.

**Comment by machikoyasuda** [comment]
> Text Links

<img width="565" alt="image" src="https://github.com/cal-itp/calitp.org/assets/3673236/27772377-935e-48ec-8feb-cc81c5430eb6">
@segacy1 The red link uses this code: `text-decoration-style: dashed;`, while the green link uses:   `text-decoration-style: dotted;`. Do you prefer Dashed or Dotted?

**Comment by machikoyasuda** [comment]
> Text Links

@segacy1 

Need regular link and hover link styles for links on:
- Links on a Press Release: Currently regular links are `calitp-primary-blue`, font-weight 700 and underlined. No hover styles. Example: https://staging.calitp.org/press/cal-itp-benefits-launch
- Links on Press and Resources page: Currently regular links are `calitp-primary-blue`, font-weight 700 and NOT underlined. Current hover style is a color change (but that's just from our code default -- we need a style to put in here). Example: https://staging.calitp.org/press
- Links on the Footer: Currently the link style is white color, regular font weight and no underline. No hover effect specified.
- Links on the Nav: Currently the link style is black color, font-weight 700 and no underline. No hover effect specified.
- Header Link on a Press Release: This little Press page back link is currently styled with `calitp-primary-blue`, font-weight 700, no underline and no hover effect specified.
<img width="205" alt="image" src="https://github.com/cal-itp/calitp.org/assets/3673236/77312a3c-3ea2-4d9c-8633-82b6d1e2ac12">

**Comment by segacy1** [comment]
@machikoyasuda let’s set the default of all links to be:
- bold
- underlined (2px thickness)

On hover:
- White links change from solid underline to dotted underline
- Regular (blue) links change from solid underline to dotted underline and use the same color treatment on hover as mobimart links (that dark blue). 

*Exceptions*
Could we remove the underline in the following instances: 
    - Nav links: can we copy the exact nav treatment we use for mobimart?
    - Little press page back link: can remove the underline here, but still have it darken on hover like the blue links on mobimart (same treatment as the table of content links in mobimart’s how-to guides, including that the text is H5 and not H4)

Press Release links look good and the links of Press and Resources should be underlined—I’ll update in Figma!
